### ISSUE TITLE
Request: zero bolus suggestion toggle

### ISSUE THREAD

**Issue by Menno86** [CustomTypeOne/LoopPatches#11]
**Request**
Add a toggle in the settings to: turn on or off the bolus suggestion. In FreeAPS the bolus suggestions was 0%. In Loop 3 the bolus suggestion is 100%. 

**Relevance**
This future prevents younger users (and people who only fill in carbs) to accidentally bolus 100% after entering or changing carbs. For many users a 100% bolus suggestion doesn't seem logical.

**Comment by marionbarker** [comment]
No promises on future improvements. But I'll keep this in mind. 

In general, the 100% bolus should be safe **when** settings are properly adjusted and carb entry is not too aggressive. But the modification of default does require a change in habits.

**Comment by bjorkert** [comment]
@Menno86 If you want it permanently off you could just make this modification and suggestion will always be zero, not using it myself but did some light testing:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/12718238/215284699-71f83c17-9386-4691-9289-038d4ac5ea44.png">

**Comment by marionbarker** [comment]
The problem with this is a bolus is never filled in on the Bolus line and there is no hidden feature to copy the recommended amount to the bolus line. It must be typed in whether coming from a meal entry or trying to get a bolus recommendation.

If you typically want small amounts, why not lower the maxBolus.

**Comment by marionbarker** [comment]
Closing this. I do not plan to add this feature to LoopPatches.
