### ISSUE TITLE
Request: add toggle for 4.8 min updates

### ISSUE THREAD

**Issue by Menno86** [CustomTypeOne/LoopPatches#13]
As has been discussed on Zullip, some users experience battery drain of pods of Medtronic pump due to one minute update cycles. The Loop docs have been update and also mention this possibility. 

On Zullip and facebook the code has been shared to limit updates to 5 minute cycles (4.8 min). 

It would be awesome if a toggle could be added to enable of disable 5 minute update cycles. 
![6B637A26-C822-4A5C-8697-44E1A5FAB261](https://user-images.githubusercontent.com/5693203/230668333-4c2fe827-4559-412e-be86-5457b455e227.png)
![AA151BAE-9296-4B5C-9497-528C81346950](https://user-images.githubusercontent.com/5693203/230668339-32e54d8f-4176-4b37-b5f6-3196f4d7e9e4.jpeg)

**Comment by marionbarker** [comment]
I prefer to add no more features to CustomTypeOne LoopPatches.

Instead with the new method for applying customizations which works for both Mac-Xcode build and GitHub Browser build methods, I point you instead to the Prepared Patch for this customization.

* [Loop and Learn: Customization: Limit Loop Cycle Time](https://www.loopandlearn.org/custom-code/#loop-cycle-time)

Please read the [Introduction to Prepared Patches](https://www.loopandlearn.org/custom-code/#prepared-patches) on that same page.

Similar information is found in [LoopDocs: Customize with GitHub](https://loopkit.github.io/loopdocs/gh-actions/gh-customize), but no prepared patches are found in that document. You need to go to the loop and learn website for those.
